// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUExAdk0xtZ6YL6L0fuyBpmQSyyjsqS3M',
    appId: '1:761905495926:android:96c1c156b30e319a510457',
    messagingSenderId: '761905495926',
    projectId: 'crudapp-1111',
    storageBucket: 'crudapp-1111.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPt3wESqZ_bUcyNpzYlevtUREiNcTjd3s',
    appId: '1:761905495926:web:abf1f793024e0746510457',
    messagingSenderId: '761905495926',
    projectId: 'crudapp-1111',
    authDomain: 'crudapp-1111.firebaseapp.com',
    storageBucket: 'crudapp-1111.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDznYq7v45r4R9avuZ3rWyN4d-kqBxc6Tc',
    appId: '1:761905495926:ios:4db5f6392f813785510457',
    messagingSenderId: '761905495926',
    projectId: 'crudapp-1111',
    storageBucket: 'crudapp-1111.firebasestorage.app',
    iosBundleId: 'com.ceduc.crudapp1111',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDznYq7v45r4R9avuZ3rWyN4d-kqBxc6Tc',
    appId: '1:761905495926:ios:4db5f6392f813785510457',
    messagingSenderId: '761905495926',
    projectId: 'crudapp-1111',
    storageBucket: 'crudapp-1111.firebasestorage.app',
    iosBundleId: 'com.ceduc.crudapp1111',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPt3wESqZ_bUcyNpzYlevtUREiNcTjd3s',
    appId: '1:761905495926:web:7b680ccf93baeb41510457',
    messagingSenderId: '761905495926',
    projectId: 'crudapp-1111',
    authDomain: 'crudapp-1111.firebaseapp.com',
    storageBucket: 'crudapp-1111.firebasestorage.app',
  );

}